/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9TykGtLcm7K
 */
import Link from "next/link"

export function Breadcrumb() {
  return (
    <div className="flex flex-wrap p-6 space-x-4">
      <Link
        className="inline-flex h-10 items-center justify-center rounded-md bg-gray-100 px-6 py-2 text-sm font-medium text-gray-900 hover:bg-gray-200 focus:outline-none"
        href="#"
      >
        <span className="mr-2">1</span>
        Introduction
      </Link>
      <ArrowRightIcon className="w-4 h-4 self-center" />
      <Link
        className="inline-flex h-10 items-center justify-center rounded-md bg-green-100 px-6 py-2 text-sm font-medium text-green-900 hover:bg-green-200 focus:outline-none"
        href="#"
      >
        <span className="mr-2">2</span>
        Questionnaire
      </Link>
      <ArrowRightIcon className="w-4 h-4 self-center" />
      <Link
        className="inline-flex h-10 items-center justify-center rounded-md bg-gray-100 px-6 py-2 text-sm font-medium text-gray-900 hover:bg-gray-200 focus:outline-none"
        href="#"
      >
        <span className="mr-2">3</span>
        Instructions
      </Link>
      <ArrowRightIcon className="w-4 h-4 self-center" />
      <Link
        className="inline-flex h-10 items-center justify-center rounded-md bg-gray-100 px-6 py-2 text-sm font-medium text-gray-900 hover:bg-gray-200 focus:outline-none"
        href="#"
      >
        <span className="mr-2">4</span>
        Card Sorting Test
      </Link>
    </div>
  )
}


function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}
