/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Qm1TUVlD8gO
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";

export function CardSortBoard() {
  return (
    <div className="grid w-full min-h-screen grid-cols-[300px_300px_300px] gap-4 p-4">
      <div>
        <Card className="h-full">
          <CardHeader className="px-4 py-2">
            <CardTitle>Category 1</CardTitle>
          </CardHeader>
          <CardContent className="overflow-auto p-4 space-y-4">
            <Card>
              <CardContent className="flex items-center justify-between">
                <div className="flex-1 ml-4">
                  <h4 className="font-medium">Card 1</h4>
                </div>
              </CardContent>
            </Card>
          </CardContent>
        </Card>
      </div>
      <div>
        <Card className="h-full">
          <CardHeader className="px-4 py-2">
            <CardTitle>Category 2</CardTitle>
          </CardHeader>
          <CardContent className="overflow-auto p-4 space-y-4">
            <Card>
              <CardContent className="flex items-center justify-between">
                <div className="flex-1 ml-4">
                  <h4 className="font-medium">Card 2</h4>
                </div>
              </CardContent>
            </Card>
          </CardContent>
        </Card>
      </div>
      <div>
        <Card className="h-full">
          <CardHeader className="px-4 py-2">
            <CardTitle>Category 3</CardTitle>
          </CardHeader>
          <CardContent className="overflow-auto p-4 space-y-4">
            <Card>
              <CardContent className="flex items-center justify-between">
                <div className="flex-1 ml-4">
                  <h4 className="font-medium">Card 3</h4>
                </div>
              </CardContent>
            </Card>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
