/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3UnZw6PPFOu
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
  CardFooter,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function CreateTest() {
  return (
    <>
      <h1 className="font-bold text-3xl my-4">Create new card sorting test </h1>
      <Card className="mb-10">
        <CardHeader>
          <CardTitle>Card Sorting Test Form</CardTitle>
          <CardDescription>
            Input the questions for the card sorting test.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="question-1">Question 1</Label>
              <Input id="question-1" placeholder="Enter your question" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="question-2">Question 2</Label>
              <Input id="question-2" placeholder="Enter your question" />
            </div>
            <Button className="self-end">Add More Questions</Button>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Create Cards and Columns</CardTitle>
          <CardDescription>
            Define the cards and categories for the card sorting test.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-4">
              <CardTitle>Categories</CardTitle>
              <div className="space-y-2">
                <Label htmlFor="column-1">Column 1</Label>
                <Input id="column-1" placeholder="Enter column name" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="column-2">Column 2</Label>
                <Input id="column-2" placeholder="Enter column name" />
              </div>
              <Button className="self-end">Add More Columns</Button>
            </div>
            <div className="space-y-4">
              <CardTitle>Cards</CardTitle>
              <div className="space-y-2">
                <Label htmlFor="card-1">Card 1</Label>
                <Input id="card-1" placeholder="Enter card name" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="card-2">Card 2</Label>
                <Input id="card-2" placeholder="Enter card name" />
              </div>
              <Button className="self-end">Add More Cards</Button>
            </div>
          </div>
        </CardContent>
        <CardFooter className="flex justify-end">
          <Button className="mr-4" variant="outline">
            Cancel
          </Button>
          <Button>Save</Button>
        </CardFooter>
      </Card>
    </>
  );
}
