/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/i3o7ZQ7GD1T
 */
import Link from "next/link";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { CreditCardIcon } from "./icons/credit-card-icon";

export function Dashboard() {
  return (
    <main className="flex-grow bg-gray-100 p-6">
      <h1 className="text-2xl font-semibold mb-4">My Tests</h1>
      <div className="grid gap-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
        <Card className="transition duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-105">
          <CardHeader className="flex flex-row items-center gap-4">
            <CreditCardIcon className="w-8 h-8" />
            <div className="grid gap-1">
              <CardTitle>Test 1</CardTitle>
              <CardDescription>Created on Dec 1, 2023</CardDescription>
            </div>
          </CardHeader>
          <CardContent className="grid gap-2">
            <div className="text-sm font-semibold">10 cards sorted</div>
            <div className="flex items-center gap-4 text-sm">
              <Badge>Completed</Badge>
            </div>
          </CardContent>
        </Card>
        <Card className="transition duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-105">
          <CardHeader className="flex flex-row items-center gap-4">
            <CreditCardIcon className="w-8 h-8" />
            <div className="grid gap-1">
              <CardTitle>Test 2</CardTitle>
              <CardDescription>Created on Nov 30, 2023</CardDescription>
            </div>
          </CardHeader>
          <CardContent className="grid gap-2">
            <div className="text-sm font-semibold">8 cards sorted</div>
            <div className="flex items-center gap-4 text-sm">
              <Badge>Completed</Badge>
            </div>
          </CardContent>
        </Card>
        <Card className="transition duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-105">
          <CardHeader className="flex flex-row items-center gap-4">
            <CreditCardIcon className="w-8 h-8" />
            <div className="grid gap-1">
              <CardTitle>Test 3</CardTitle>
              <CardDescription>Created on Nov 29, 2023</CardDescription>
            </div>
          </CardHeader>
          <CardContent className="grid gap-2">
            <div className="text-sm font-semibold">15 cards sorted</div>
            <div className="flex items-center gap-4 text-sm">
              <Badge>Completed</Badge>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
