/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UpAdSnHxQQ9
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Home() {
  return (
    <div className="h-screen flex flex-col justify-center items-center bg-gray-50 text-center px-4 sm:px-6 lg:px-8">
      <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold mb-4">
        Welcome to KartSort
      </h1>
      <p className="text-sm sm:text-base md:text-lg lg:text-xl text-gray-600 max-w-lg mx-auto mb-8">
        A revolutionary app that simplifies card sorting and improves your
        workflow.
      </p>
      <Card className="mb-8 w-full max-w-xs sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl mx-auto">
        <CardHeader>
          <CardTitle className="text-xl sm:text-2xl">Get Started</CardTitle>
          <CardDescription className="text-gray-500">
            Sign up and start sorting your cards now.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Link href="/register">
            <Button className="w-full h-10 bg-blue-500 text-white rounded-md">
              Sing up
            </Button>
          </Link>
        </CardContent>
      </Card>
      <p className="text-xs sm:text-sm md:text-base lg:text-lg text-gray-500">
        Already have an account?
        <Link className="text-blue-500 hover:underline" href="/login">
          Log in
        </Link>
      </p>
    </div>
  );
}
