/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nH8fNO3fpxV
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Login() {
  return (
    <div className="flex items-center justify-center h-screen bg-gray-200">
      <div className="bg-white  p-10 rounded-lg shadow-lg w-96">
        <h1 className="text-3xl font-bold mb-6 text-center">Login</h1>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="username">Username</Label>
            <Input
              id="username"
              placeholder="Enter your username"
              required
              type="text"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input id="password" required type="password" />
          </div>
          <Button className="w-full" type="submit">
            Login
          </Button>
          <div className="flex justify-between items-center mt-4">
            <Link
              className=" sm:text-sm md:text-base lg:text-lg text-gray-500 text-sm underline"
              href="#"
            >
              Forgot your password?
            </Link>
            <Link
              className="text-xs sm:text-sm md:text-base lg:text-lg  underline text-blue-500"
              href="/register"
            >
              Register
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
