/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XzMKMJsALbh
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Register() {
  return (
    <div className=" mx-auto max-w-sm sm:max-w-md lg:max-w-lg xl:max-w-xl 2xl:max-w-2xl space-y-6 bg-white  shadow-lg rounded-lg p-6">
      <div className="flex justify-center items-center flex-col sm:flex-row">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold text-center">Register</h1>
          <p className="text-zinc-500 dark:text-zinc-400 text-center">
            Please fill out the form to create an account
          </p>
        </div>
      </div>
      <div className="space-y-4">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="first-name">First name</Label>
            <Input id="first-name" placeholder="John" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="last-name">Last name</Label>
            <Input id="last-name" placeholder="Doe" required />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input
            id="email"
            placeholder="johndoe@example.com"
            required
            type="email"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input id="password" required type="password" />
        </div>
        <Button className="w-full" type="submit">
          Register
        </Button>
      </div>
      <div className="mt-4 text-center">
        <p className="text-xs sm:text-sm md:text-base lg:text-lg text-gray-500">
          Already have an account?
          <Link className="text-blue-500 hover:underline" href="/login">
            Log in
          </Link>
        </p>
      </div>
    </div>
  );
}
